### ISSUE TITLE
Tradução em inglês da descrição do repositório

### ISSUE THREAD

**Issue by panisson** [dieegom/brumadinho_location#11]
A tradução em língua inglesa da descrição do projeto e de alguns dos issues onde é necessária ajuda na implementação poderia abrir para a contribuição de uma platéia muito maior de de pesquisadores especialistas no assunto.
No momento não é possível compartilhar e pedir a contribuição de pessoas que não entendem português.

**Comment by brunocroh** [comment]
Seria legal junto com a Tradução, dar uma melhorada no [README.md](https://github.com/dieegom/brumadinho_location/blob/master/README.md)

**Comment by rfschubert** [comment]
já fiz e coloquei um PR sobre isso @brunocroh

**Comment by vaniaon** [comment]
Pessoal, fiz a tradução... Se tiver algum problema, podem reabrir
