### ISSUE TITLE
Domínio

### ISSUE THREAD

**Issue by wandersonwhcr** [dieegom/brumadinho_location#18]
Precisam de domínio? De máquina para hospedagem?

**Comment by wandersonwhcr** [comment]
Eu crio uma por minha conta na DO se quiser. Posso correr atrás de domínio, também.

**Comment by endersonmaia** [comment]
de acordo com o README, já tá hospedado no IP 18.218.138.85 , se criar domínio, aponta pra este IP

**Comment by qgustavor** [comment]
Assim que configurarem o domínio seria interessante usar HTTPS e HTTP/2.

**Comment by vaniaon** [comment]
Pessoal,
Estamos desenvolvendo outras ferramentas em paralelo, então seria interessante hospedá-las, sim.
Deem uma olhada nos projetos que já estão prontos e acho que podem ir colocando em homologação

**Comment by andrebassi** [comment]
@vaniaon -> Se precisarem de ajuda com infra, me acionem.

Até mesmo com o domínio se já tiverem sugestões.

**Comment by wandersonwhcr** [comment]
Estou criando o domínio osei.ong.br (Open Source for Environmental Impacts)
Vou adicionar um subdomínio brumadinho.osei.ong.br
Vou criar uma máquina com um proxy reverso em NGINX apontando para o IP da documentação.
Vou instalar SSL com o Certbot.

**Comment by endersonmaia** [comment]
@wandersonwhcr talvez por ora, um registro no DNS resolva, ex.: `brumadinho.osei.ong.br -> 18.218.138.85`, e já é mais imediato

quanto ao NGINX e SSL, faria num segundo passo, e talvez seria interessante ver quem tá responsável por essa hospedagem no `18.218.138.85` e tentar criar essa configuração de SSL por lá lá, o que acha ?

**Comment by wandersonwhcr** [comment]
já estou terminando :)

**Comment by endersonmaia** [comment]
> já estou terminando :)

só fiquei receoso do atraso que o nginx proxy poderia adicionar, estando ele em outro host, poderia adicionar aí, talvez não seja problema inicialmente

**Comment by wandersonwhcr** [comment]
atraso? tem nenhum, pode ficar tranquilo.
se der problemas nos acessos, eu faço um microcache via nginx, também.

**Comment by wandersonwhcr** [comment]
Está demorando um pouco para virar o domínio para o NS da Digital Ocean. Quando estiver 100%, informo aqui.

**Comment by wandersonwhcr** [comment]
Pronto.

https://brumadinho.osei.ong.br/

Se alguém não conseguir abrir ainda, está virando o DNS. Coloquei o TTL em 60 para uma migração rápida, caso necessidade. Se alguém quiser testar se está tudo OK, basta:

```
dig @8.8.8.8 brumadinho.osei.ong.br
```

**Comment by lbenetti** [comment]
> Pronto.
> 
> https://brumadinho.osei.ong.br/
> 
> Se alguém não conseguir abrir ainda, está virando o DNS. Coloquei o TTL em 60 para uma migração rápida, caso necessidade. Se alguém quiser testar se está tudo OK, basta:
> 
> ```
> dig @8.8.8.8 brumadinho.osei.ong.br
> ```

Funcionando aqui!

**Comment by Lrodlima** [comment]
> Pronto.
> 
> https://brumadinho.osei.ong.br/
> 
> Se alguém não conseguir abrir ainda, está virando o DNS. Coloquei o TTL em 60 para uma migração rápida, caso necessidade. Se alguém quiser testar se está tudo OK, basta:
> 
> ```
> dig @8.8.8.8 brumadinho.osei.ong.br
> ```

Legal, acho que agora só falta mudar lá na documentação para esse domínio
