### ISSUE TITLE
Enhance information about victims

### ISSUE THREAD

**Issue by endersonmaia** [dieegom/brumadinho_location#27]
There are some lists with the names of the missing or deceased people.

[This list](
http://www.vale.com/brasil/PT/aboutvale/servicos-para-comunidade/minas-gerais/atualizacoes_brumadinho/Documents/PDFs/lista28-01-201914h15.pdf) from Defesa Civil is PDF, and could be merged with other spreadsheets ([1](https://docs.google.com/spreadsheets/d/120JXqEF8Mil7Ex_ty9tbdfNAYqZpYyJ7PIYu46teUJY/edit#gid=0), [2](https://docs.google.com/spreadsheets/d/1M2AxPtzonn2Q4QWPdiW5UE8DeylO_tTGgoJ9Vkitf4E/edit#gid=0)) to enhance it's data.

**Comment by endersonmaia** [comment]
#geo, #info

**Comment by onilton** [comment]
Does anyone know for what this info would be useful for?

**Comment by endersonmaia** [comment]
@onilton the idea, as discusses at #8 , is to estimate the geolocation of people based on information about them

**Comment by eduardolomb** [comment]
hmmmm...I don't know how to do it. I personally don't think viable to scrape social network data from the information given at the pdf/spreadsheets.

**Comment by vaniaon** [comment]
https://github.com/dieegom/brumadinho_location/tree/master/crawler
