### ISSUE TITLE
File "/usr/lib/python3.6/configparser.py", line 1138, in _unify_values

### ISSUE THREAD

**Issue by romulogarofalo** [dieegom/brumadinho_location#34]
i'm trying to install the project, I already install the dependencies with pip3 but got this error

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'server'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "backend/servico.py", line 44, in <module>
    cfg_port = cfg.getint('server', 'port')
  File "/usr/lib/python3.6/configparser.py", line 819, in getint
    fallback=fallback, **kwargs)
  File "/usr/lib/python3.6/configparser.py", line 809, in _get_conv
    **kwargs)
  File "/usr/lib/python3.6/configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'server'
```

**Comment by eduardolomb** [comment]
Probably the server isn't running in your machine. I'm getting the same error....I'll try to solve it again tomorrow.

**Comment by romulogarofalo** [comment]
I solved a part, and now the server can run but the requests does't work idk why

to run the server (on your machine) you need to comment a part of the code
![screenshot from 2019-01-28 21-53-49](https://user-images.githubusercontent.com/18492592/51874273-7ee38180-2347-11e9-9bc0-80fea84d2ece.png)

**Comment by romulogarofalo** [comment]
should I close the issue?

**Comment by volneyrock** [comment]
You can also create a "config.ini" file like this:
![captura de tela_2019-01-29_01-07-06](https://user-images.githubusercontent.com/8210627/51881623-07bbe680-2363-11e9-90d9-3f44b2025e58.png)

**Comment by vaniaon** [comment]
Guys, it seems that you already solve the problem. I will close this issue.
