### ISSUE TITLE
Do you all agree with making an adaptation of this project to django framework? If yes, i'll be starting the work.

### ISSUE THREAD

**Issue by rodgomesc** [dieegom/brumadinho_location#37]

**Comment by brunocroh** [comment]
penso que uma api em flask, atende melhor fica mais flexivel a tecnogia no frontend podendo se utilizar de algum framework javascript por exemplo

**Comment by brunolcarli** [comment]
**Protuguês BR**
Minha resposta: Sim eu concordo, django é um bom framework web eu poderia colaborar nisto.

**English**
Yes, i agree, django is a good framework and i can colaborate on the project.

**Comment by alexsandro-xpt** [comment]
Flask +1

**Comment by GoDllkE** [comment]
Django would be nice but add complexity and may slow down a bit the development while flask is too lightweight to generate and publish new features. I would stick with Flask.

**Comment by thecylax** [comment]
@brunocroh, this is also possible with Django, the service only needs to provide an API, be flask, Django or pure python.

**Comment by rodgomesc** [comment]
@vaniaon , it is not a matter of being comfortable, we should choose a technology that reaches a larger number of developers, and I think the django community is being one of the biggest today

**Comment by vaniaon** [comment]
@rodgomesc My suggestion is doing small services (aka microservices), not the entire project. If we work in this way, we can reach even more people ;)

**Comment by brunolcarli** [comment]
I agree with @rodgomesc django community is very large.

Django can be used as microservice, maybe we can use docker to host all the django services as containers in a single host server

**Comment by vaniaon** [comment]
@brunolcarli that is the idea of microservices... as also not being restricted to a single language.

By the way, the dev responsible for the original project is using django in the next realese :)

**Comment by Mendes11** [comment]
Hi, I'm closing this issue since current release is already using django!

Thanks for the suggestions
