### ISSUE TITLE
Backend - where we had searched

### ISSUE THREAD

**Issue by vaniaon** [dieegom/brumadinho_location#41]
Create a service that receives geolocations info as parameter and stores it in a data repository.
This service also needs to provide a list of all locations already visited.

Related #40

**Comment by brunolcarli** [comment]
Can this be a django app running with serializers?
The API will receive CRUD and display data as json that will be consumed by the front-end.

![captura de tela 2019-01-29 as 00 15 54](https://user-images.githubusercontent.com/14935269/51879581-35049680-235b-11e9-823e-d4ca65bdbf1a.png)
![captura de tela 2019-01-29 as 00 16 04](https://user-images.githubusercontent.com/14935269/51879582-35049680-235b-11e9-96e2-141f2b8f2714.png)
![captura de tela 2019-01-29 as 00 16 19](https://user-images.githubusercontent.com/14935269/51879583-359d2d00-235b-11e9-8c1f-8c694548b8fb.png)

**Comment by brunolcarli** [comment]
I've sent a PR withe the project, hope it helps.

Gotta work to do in it like change the database used (actually using SQLite but not recommended), and find a server to host it.

Later after my work i'll refine this, and sure all hel is needed to develop it.

**Comment by vaniaon** [comment]
Just saw your comment and updated the project readme. 
As I said there, the first in the project can choose the language and technology  :)

**Comment by vaniaon** [comment]
PR #43

**Comment by vaniaon** [comment]
O projeto está em https://github.com/dieegom/brumadinho_location/tree/develop/geolocations_service/service na  branch develop

**Comment by JBezerra** [comment]
@brunolcarli Tudo certo cara? tou com tua aplicação rodando aqui, eu so nao entendi o intuito dos 2 endpoints, no /geolocations/ ele cadastra os locais por Lat e Long via POST e via GET ele mostra os locais que ja foram visitados em Lat e Long, beleza.

Mas nao entendi porque no /visited_locations/ eu posso escolher uma Lat e uma Long cadastra no /geolocations/ e dar um nome a ela se no /visited_locations/ quando a gente pega a lista completa via GET eu nao tenho acesso ao nome que eu dei a sua respectiva Lat e Long, qual o intuito desse endpoint?

**Comment by brunolcarli** [comment]
@JBezerra criei o endpoint `/api/geolocations/` para poder cadastrar, listar e recuperar todas as localizações de que tenhamos certeza que pertence a zona afetada.

No endpoint `/api/visited_locations/` poderá cadastrar e  uma região específica baseada em sua localização, e identificá-la por uma referencia. Na última atualização que estou a trabalhar agora este endpoint receberá mais um campo para data de investigação desta localização e número de pessoas encontradas nesta localização.

Adicionarei também um endpoint `/api/found_people/` para cadastrar e recuperar informações de pessoas encontradas, incluindo nome, localização, gênero e condição de saúde.

**Comment by brunolcarli** [comment]
@JBezerra  vou fazer!

**Comment by brunolcarli** [comment]
Ok to meio perdido aqui tentando fazer funcionar nesse padrão.

Ajustei todos os paranauês pra rodar com posgresql e tenho a tela do enpoint sem dados assim:

![captura de tela 2019-01-31 as 23 07 37](https://user-images.githubusercontent.com/14935269/52096161-08e05400-25ad-11e9-84cf-83eea9723c24.png)

**Comment by brunolcarli** [comment]
Mas não sei como inserir dados aqui, todas as formas que tento ele da um erro diferente:

**Comment by brunolcarli** [comment]
desta forma está correto @JBezerra ?

![captura de tela 2019-02-01 as 00 37 46](https://user-images.githubusercontent.com/14935269/52099263-aa6da280-25b9-11e9-9fc3-9927f573d700.png)

**Comment by JBezerra** [comment]
@brunolcarli perfeito!!!! valeu monstro, so da push que eu ja modifico o meu aqui pra pegar da API

**Comment by brunolcarli** [comment]
Vou dar push aqui pra que vc possa dar continuidade no seu trabalho, ams tenho que corrigir várias coisas ainda, a começar pelo campo de input deste endpoint.

ele está esperando:

```
{
    "latitude": Float,
    "longitude": Float,
    "coordinates": null
}
```

Deixei o coordinates como opcional pois ele NAO DEVE ser preenchido, se preencher ele de forma que não receba um objeto Point() definido pelo `django.contrib.gis.geos` vai retornar um erro. Então não forneça nada ou forneça `null` para este campo e preencha somente `latitude` e `longitude` pelo menos até eu achar uma forma de consertar isso.

:D

**Comment by brunolcarli** [comment]
Ah e tive um trabalhinho pra ajustar as novas configs, me avise aqui se tiver problemas pra configurar o serviço, agora está rodando com posgresql

**Comment by brunolcarli** [comment]
@JBezerra como sugerido pelo @cacarrara  as settings devem ser criadas em um arquivo `.env` na raiz desta aplicação, padronizando com o projeto em /`core` deste repositório.

para lhe adiantar tempo eis aqui o arquivo modo como eu usei:

```
DEBUG=TRUE
SECRET_KEY=&@9mr668o!*p1=jk$=#i+l5z4*qg)s1_ey!+i*o@&%!t#c+ra2
ALLOWED_HOSTS=*

DB_NAME=geoservice
DB_USER=lem4fia
DB_PASSWORD=root
DB_HOST=localhost
DB_PORT=5432
```

provavelmente vc vai precisar o valor das variáveis DB para coincidir com as configuraçõs rodando em seu banco de dados.

crie um arquivo chamado `.env` e coloque-o na raiz do serviço:
![captura de tela 2019-02-01 as 07 54 57](https://user-images.githubusercontent.com/14935269/52115821-b461c680-25f6-11e9-9852-cc5652361d33.png)


isso deve funcionar

**Comment by JBezerra** [comment]
@brunolcarli me da teu contato pessoal pra agt conseguir se comunicar com mais facilidade, eu consegui aqui instalar o postgre na minha maquina mas estou tendo outros erros, por exemplo da uma olhadinha aqui 

![screen shot 2019-02-01 at 13 48 34](https://user-images.githubusercontent.com/20017845/52136972-29012900-2628-11e9-8d98-ca16d54bcc1b.png)

isso acontece eu creio porque eu nao rodei o migrate, mas quando eu tento rodar da isso

![screen shot 2019-02-01 at 13 49 47](https://user-images.githubusercontent.com/20017845/52137014-3fa78000-2628-11e9-856e-36841a7c7c0c.png)

ai eu tou meio perdido pq nunca fiz nada com Django

**Comment by brunolcarli** [comment]
@JBezerra meu whats: 41 99828-7053
