### ISSUE TITLE
Whatsapp group is full

### ISSUE THREAD

**Issue by jersobh** [dieegom/brumadinho_location#53]
We should bring the discussion group to telegram

**Comment by brunobehnken** [comment]
Thumbs up for Telegram

**Comment by jersobh** [comment]
Thumbs up for Telegram

**Comment by nibri10** [comment]
Telegram group available? Link?

**Comment by jersobh** [comment]
any news???

**Comment by jeancsanchez** [comment]
@dieegom ?

**Comment by vaniaon** [comment]
@nibri10 @jersobh @jeancsanchez @brunobehnken @renanvieira 
Guys, here the invitation to Telegram Group:

https://t.me/joinchat/K2pTZk1Xjo0UEzmCzkJvXQ

I will close this issue.
