### ISSUE TITLE
Get location by click on map 

### ISSUE THREAD

**Issue by LuanSSouza** [dieegom/brumadinho_location#59]
When the user clicks on the map, the input fields must be filled with the location data

**Comment by filipesiegrist** [comment]
I am trying to do this, but I'm having some scopes problems.
In theory it's easy, just add an dblclick event, but the javascript code initializes the map in a function and the page doesn't recognizes the event:

This is what I'm trying to do:

`window.ma.on('click',function(e){
		lat = e.latlng.lat;
		lon = e.latlng.lng;
		document.getElementById("lat").value = lat;
		document.getElementById("lng").value = lon;
		calculate();
	});
`

**Comment by Mendes11** [comment]
There is already a PR regarding this issue. Although it's to the develop branch, which is outdated #55

**Comment by LuanSSouza** [comment]
Yes. I will try to make a PR with the changes to the master branch.
