### ISSUE TITLE
Why are you taking so long to merge new pull requests? 

### ISSUE THREAD

**Issue by rodgomesc** [dieegom/brumadinho_location#77]

**Comment by endersonmaia** [comment]
@rodgomesc it's not an easy task to make sure everything is working before merging

but, you can still make your own fork, and merge it all yourself, and if you guarantee that it's working, you can make a new PR, that includes all the other, that should accelerate the process

**Comment by rodgomesc** [comment]
I can do this but I will only have free time weekend
